# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from random import randint
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 156)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.action_2.triggered.connect(self.chit)
        self.action.triggered.connect(self.da)
        
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def da (self):
        try:
            f = open('spisok.txt', 'r', encoding="utf-8")
            self.fp=f.read()
            self.lineEdit.setText(str(self.fp))
# Вывести результат для контроля
            flag = 0
            i = 1
            while i < len(self.fp):
                if(self.fp[i] < self.fp[i - 1]):
                    flag = 1
                i += 1
                
            self.lineEdit.setText(str(self.fp))
            print(i)
            if (not flag) :
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Warning)
                msg.setText("Список отсортирован!")
                msg.exec_()
                print ("")
            else :
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Warning)
                msg.setText("Список не отсортирован!")
                
                msg.setWindowTitle("Внимание")
                
                msg.exec_()
            

           
            print("lst = ", lst)
            #  Сохранить список в текстовом файле
            #  Открыть файл для записи
            f = open('file.txt', 'wt')
            s = str(lst) # Конвертировать целое число в строку
            f.write(s + '\n') # Записать строку

            self.lineEdit.setText(str(lst))
            
        except Exception as e:
            print(e)

    def chit(self):
        i = 0
        self.test_list= []
        while i<10:
            number = randint(0, 101) # число от 0 до 100
            self.test_list = self.test_list+ [number]
            i = i+1
        
        print ("Original list : " + str(self.test_list))
        flag = 0
        i = 1
        while i < len(self.test_list):
            if(self.test_list[i] < self.test_list[i - 1]):
                flag = 1
            i += 1
            
            self.lineEdit.setText(str(self.test_list))
            print(i)
        if (not flag) :
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Список отсортирован!")
            msg.exec_()
            print ("")
        else :
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Список не отсортирован!")
            
            msg.setWindowTitle("Внимание")
            
            msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сортировка списков"))
        self.label.setText(_translate("MainWindow", "Список чисел:"))
        self.pushButton_2.setText(_translate("MainWindow", "Выход"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Считать из файла "))
        self.action_2.setText(_translate("MainWindow", "Считать из файла случайный список"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
