# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 474)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 471, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setGeometry(QtCore.QRect(10, 80, 391, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 120, 391, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 170, 411, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(370, 230, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 401, 61))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 80, 381, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 120, 361, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 160, 391, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 230, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 371, 51))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 230, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_7.setGeometry(QtCore.QRect(30, 80, 351, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 120, 381, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_9.setGeometry(QtCore.QRect(30, 170, 381, 17))
        self.radioButton_9.setObjectName("radioButton_9")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 381, 51))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_10.setGeometry(QtCore.QRect(30, 90, 351, 17))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_11.setGeometry(QtCore.QRect(30, 130, 381, 17))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_12.setGeometry(QtCore.QRect(30, 170, 401, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 240, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 371, 51))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.radioButton_13 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_13.setGeometry(QtCore.QRect(30, 90, 371, 17))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_14.setGeometry(QtCore.QRect(30, 130, 381, 17))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_15.setGeometry(QtCore.QRect(30, 170, 391, 17))
        self.radioButton_15.setObjectName("radioButton_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 230, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 361, 51))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.radioButton_16 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_16.setGeometry(QtCore.QRect(30, 90, 411, 17))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_17.setGeometry(QtCore.QRect(30, 130, 381, 17))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_18.setGeometry(QtCore.QRect(30, 170, 401, 17))
        self.radioButton_18.setObjectName("radioButton_18")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setGeometry(QtCore.QRect(380, 240, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 371, 61))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.radioButton_19 = QtWidgets.QRadioButton(self.tab_7)
        self.radioButton_19.setGeometry(QtCore.QRect(30, 80, 371, 17))
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(self.tab_7)
        self.radioButton_20.setGeometry(QtCore.QRect(30, 120, 311, 17))
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_21 = QtWidgets.QRadioButton(self.tab_7)
        self.radioButton_21.setGeometry(QtCore.QRect(30, 160, 361, 17))
        self.radioButton_21.setObjectName("radioButton_21")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 230, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_8 = QtWidgets.QLabel(self.tab_7)
        self.label_8.setGeometry(QtCore.QRect(40, 20, 341, 51))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.radioButton_22 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_22.setGeometry(QtCore.QRect(20, 70, 371, 17))
        self.radioButton_22.setObjectName("radioButton_22")
        self.radioButton_23 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_23.setGeometry(QtCore.QRect(20, 110, 371, 17))
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_24 = QtWidgets.QRadioButton(self.tab_8)
        self.radioButton_24.setGeometry(QtCore.QRect(20, 150, 381, 17))
        self.radioButton_24.setObjectName("radioButton_24")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_8.setGeometry(QtCore.QRect(370, 240, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_9 = QtWidgets.QLabel(self.tab_8)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 331, 41))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.radioButton_28 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_28.setGeometry(QtCore.QRect(20, 90, 411, 17))
        self.radioButton_28.setObjectName("radioButton_28")
        self.radioButton_29 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_29.setGeometry(QtCore.QRect(20, 130, 391, 17))
        self.radioButton_29.setObjectName("radioButton_29")
        self.radioButton_30 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_30.setGeometry(QtCore.QRect(20, 180, 391, 17))
        self.radioButton_30.setObjectName("radioButton_30")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_10.setGeometry(QtCore.QRect(370, 230, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_11 = QtWidgets.QLabel(self.tab_10)
        self.label_11.setGeometry(QtCore.QRect(30, 20, 331, 61))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.radioButton_25 = QtWidgets.QRadioButton(self.tab_9)
        self.radioButton_25.setGeometry(QtCore.QRect(20, 90, 381, 17))
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(self.tab_9)
        self.radioButton_26.setGeometry(QtCore.QRect(20, 130, 421, 17))
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_27 = QtWidgets.QRadioButton(self.tab_9)
        self.radioButton_27.setGeometry(QtCore.QRect(20, 180, 401, 17))
        self.radioButton_27.setObjectName("radioButton_27")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_9.setGeometry(QtCore.QRect(380, 240, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 331, 51))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.radioButton_31 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_31.setGeometry(QtCore.QRect(20, 90, 391, 17))
        self.radioButton_31.setObjectName("radioButton_31")
        self.radioButton_32 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_32.setGeometry(QtCore.QRect(20, 130, 421, 17))
        self.radioButton_32.setObjectName("radioButton_32")
        self.radioButton_33 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_33.setGeometry(QtCore.QRect(20, 160, 401, 17))
        self.radioButton_33.setObjectName("radioButton_33")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_11.setGeometry(QtCore.QRect(390, 240, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_12 = QtWidgets.QLabel(self.tab_11)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 371, 41))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.radioButton_34 = QtWidgets.QRadioButton(self.tab_12)
        self.radioButton_34.setGeometry(QtCore.QRect(30, 80, 381, 17))
        self.radioButton_34.setObjectName("radioButton_34")
        self.radioButton_35 = QtWidgets.QRadioButton(self.tab_12)
        self.radioButton_35.setGeometry(QtCore.QRect(30, 120, 381, 17))
        self.radioButton_35.setObjectName("radioButton_35")
        self.radioButton_36 = QtWidgets.QRadioButton(self.tab_12)
        self.radioButton_36.setGeometry(QtCore.QRect(30, 160, 411, 17))
        self.radioButton_36.setObjectName("radioButton_36")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_12.setGeometry(QtCore.QRect(380, 240, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_13 = QtWidgets.QLabel(self.tab_12)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 371, 41))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.radioButton_37 = QtWidgets.QRadioButton(self.tab_13)
        self.radioButton_37.setGeometry(QtCore.QRect(20, 80, 371, 17))
        self.radioButton_37.setObjectName("radioButton_37")
        self.radioButton_38 = QtWidgets.QRadioButton(self.tab_13)
        self.radioButton_38.setGeometry(QtCore.QRect(20, 120, 391, 17))
        self.radioButton_38.setObjectName("radioButton_38")
        self.radioButton_39 = QtWidgets.QRadioButton(self.tab_13)
        self.radioButton_39.setGeometry(QtCore.QRect(20, 160, 381, 17))
        self.radioButton_39.setObjectName("radioButton_39")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_13.setGeometry(QtCore.QRect(380, 230, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_14 = QtWidgets.QLabel(self.tab_13)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 401, 51))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.radioButton_40 = QtWidgets.QRadioButton(self.tab_14)
        self.radioButton_40.setGeometry(QtCore.QRect(10, 80, 411, 17))
        self.radioButton_40.setObjectName("radioButton_40")
        self.radioButton_41 = QtWidgets.QRadioButton(self.tab_14)
        self.radioButton_41.setGeometry(QtCore.QRect(10, 120, 431, 17))
        self.radioButton_41.setObjectName("radioButton_41")
        self.radioButton_42 = QtWidgets.QRadioButton(self.tab_14)
        self.radioButton_42.setGeometry(QtCore.QRect(10, 160, 431, 17))
        self.radioButton_42.setObjectName("radioButton_42")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_14.setGeometry(QtCore.QRect(370, 240, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_15 = QtWidgets.QLabel(self.tab_14)
        self.label_15.setGeometry(QtCore.QRect(30, 20, 351, 51))
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.radioButton_43 = QtWidgets.QRadioButton(self.tab_15)
        self.radioButton_43.setGeometry(QtCore.QRect(30, 90, 371, 17))
        self.radioButton_43.setObjectName("radioButton_43")
        self.radioButton_44 = QtWidgets.QRadioButton(self.tab_15)
        self.radioButton_44.setGeometry(QtCore.QRect(30, 130, 371, 17))
        self.radioButton_44.setObjectName("radioButton_44")
        self.radioButton_45 = QtWidgets.QRadioButton(self.tab_15)
        self.radioButton_45.setGeometry(QtCore.QRect(30, 170, 381, 17))
        self.radioButton_45.setObjectName("radioButton_45")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_15.setGeometry(QtCore.QRect(380, 230, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label = QtWidgets.QLabel(self.tab_15)
        self.label.setGeometry(QtCore.QRect(30, 10, 351, 51))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_15, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ТЕСТ ПО ОП"))

        
        self.radioButton.setText(_translate("Dialog", "Гвидо ван Россум"))
        self.radioButton_2.setText(_translate("Dialog", "Джеймс Гослинг"))
        self.radioButton_3.setText(_translate("Dialog", "Деннис Ритчи"))
        self.pushButton.setText(_translate("Dialog", "Следующий"))
        self.label_2.setText(_translate("Dialog", "Кто является создателем языка Python?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Dialog", "Вопрос 1"))
        self.radioButton_4.setText(_translate("Dialog", "набор шагов, осуществляющих последовательность раюботы программы"))
        self.radioButton_5.setText(_translate("Dialog", "инструкция для компьютеров"))
        self.radioButton_6.setText(_translate("Dialog", "ничего"))
        self.pushButton_2.setText(_translate("Dialog", "Следующий"))
        self.label_3.setText(_translate("Dialog", "Что такое алгоритм?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Вопрос 2"))
        self.pushButton_3.setText(_translate("Dialog", "Следующий"))
        self.radioButton_7.setText(_translate("Dialog", "интерактивный язык низкого уровня, работающий с машинным кодом"))
        self.radioButton_8.setText(_translate("Dialog", "язык программирования"))
        self.radioButton_9.setText(_translate("Dialog", "совокупность языков"))
        self.label_4.setText(_translate("Dialog", "Что такое ассемблер?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Вопрос 3"))
        self.radioButton_10.setText(_translate("Dialog", "это while, for и elif"))
        self.radioButton_11.setText(_translate("Dialog", "оператор языка программирования, позволяющий многократно повторять одну и ту же последовательность команд"))
        self.radioButton_12.setText(_translate("Dialog", "структура"))
        self.pushButton_4.setText(_translate("Dialog", "Следующий"))
        self.label_5.setText(_translate("Dialog", "Что такое цикл?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Вопрос 4"))
        self.radioButton_13.setText(_translate("Dialog", "перевод типа элемента из одного в другой"))
        self.radioButton_14.setText(_translate("Dialog", "помощь в переводе элементов в другой тип"))
        self.radioButton_15.setText(_translate("Dialog", "распознование переменных"))
        self.pushButton_5.setText(_translate("Dialog", "Следующий"))
        self.label_6.setText(_translate("Dialog", "Что такое ретипизация?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Вопрос 5"))
        self.radioButton_16.setText(_translate("Dialog", "кроссплатформенныйт интиерпретируемый язык высокого уровня"))
        self.radioButton_17.setText(_translate("Dialog", "язык программирования"))
        self.radioButton_18.setText(_translate("Dialog", "объектно-ориентированный язык программирования"))
        self.pushButton_6.setText(_translate("Dialog", "Следующий"))
        self.label_7.setText(_translate("Dialog", "Что такое Python?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Вопрос 6"))
        self.radioButton_19.setText(_translate("Dialog", "правила написания корректного кода"))
        self.radioButton_20.setText(_translate("Dialog", "набор каких-то правил"))
        self.radioButton_21.setText(_translate("Dialog", "мы это проходили?"))
        self.pushButton_7.setText(_translate("Dialog", "Следующий"))
        self.label_8.setText(_translate("Dialog", "Что такое PEP 8?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Вопрос 7"))
        self.radioButton_22.setText(_translate("Dialog", "извлечение из данной строки одного символа или некоторого фрагмента подстроки или подпоследовательности"))
        self.radioButton_23.setText(_translate("Dialog", "извлечение из данной строки и считывание по функции"))
        self.radioButton_24.setText(_translate("Dialog", "правило извлечения"))
        self.pushButton_8.setText(_translate("Dialog", "Следующий"))
        self.label_9.setText(_translate("Dialog", "Что такое срез?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "Вопрос 8"))
        self.radioButton_28.setText(_translate("Dialog", "в основном используются, когда необходимо создать гибкую структуру данных, обеспечивающую возможность быстрого поиска"))
        self.radioButton_29.setText(_translate("Dialog", "используются для считывания"))
        self.radioButton_30.setText(_translate("Dialog", "просто красивол расположились"))
        self.pushButton_10.setText(_translate("Dialog", "Следующий"))
        self.label_11.setText(_translate("Dialog", "Для чего нужны словари в Python?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("Dialog", "Вопрос 9"))
        self.radioButton_25.setText(_translate("Dialog", "1991"))
        self.radioButton_26.setText(_translate("Dialog", "1986"))
        self.radioButton_27.setText(_translate("Dialog", "R2005"))
        self.pushButton_9.setText(_translate("Dialog", "Следующий"))
        self.label_10.setText(_translate("Dialog", "В каком году был разработан Python?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Dialog", "Вопрос 10"))
        self.radioButton_31.setText(_translate("Dialog", "это парадигма разработки, набор правил и критериев, по которым пишут код"))
        self.radioButton_32.setText(_translate("Dialog", "бъектно-ориентированное программирование"))
        self.radioButton_33.setText(_translate("Dialog", "язык абстракций"))
        self.pushButton_11.setText(_translate("Dialog", "Следующий"))
        self.label_12.setText(_translate("Dialog", "Что такое ООП?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("Dialog", "Вопрос 11"))
        self.radioButton_34.setText(_translate("Dialog", "документировать, изучать, планировать, совершенствовать и объяснять сложные процессы с помощью простых логичных диаграмм"))
        self.radioButton_35.setText(_translate("Dialog", "расписывать процесс кодирования"))
        self.radioButton_36.setText(_translate("Dialog", "иметь представление, как реализовывать программу"))
        self.pushButton_12.setText(_translate("Dialog", "Следующий"))
        self.label_13.setText(_translate("Dialog", "Для чего нужны блок-схемы?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("Dialog", "Вопрос 12"))
        self.radioButton_37.setText(_translate("Dialog", "схематичное представление процесса, системы или компьютерного алгоритма"))
        self.radioButton_38.setText(_translate("Dialog", "набор геометрических фигур"))
        self.radioButton_39.setText(_translate("Dialog", "структурированное представление процесса программмироваия"))
        self.pushButton_13.setText(_translate("Dialog", "Следующий"))
        self.label_14.setText(_translate("Dialog", "Что такое блок-схема?"))

        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("Dialog", "Вопрос 13"))
        self.radioButton_40.setText(_translate("Dialog", "вещественный тип данных"))
        self.radioButton_41.setText(_translate("Dialog", "целочисленный тип данных"))
        self.radioButton_42.setText(_translate("Dialog", "комплексный тип данных"))
        self.pushButton_14.setText(_translate("Dialog", "Следующий"))
        self.label_15.setText(_translate("Dialog", "Что такое float?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("Dialog", "Вопрос 14"))

        
        self.radioButton_43.setText(_translate("Dialog", "компилируемый, статически типизированный язык программирования общего назначения"))
        self.radioButton_44.setText(_translate("Dialog", "язык программирования"))
        self.radioButton_45.setText(_translate("Dialog", "язык со строгой типизацией"))
        self.pushButton_15.setText(_translate("Dialog", "Завершить"))
        self.label.setText(_translate("Dialog", "Что такое C++?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("Dialog", "Вопрос 15"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

